"""
RFC 9457 Problem Details for HTTP APIs
"""
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field

class ProblemDetails(BaseModel):
    """
    RFC 9457 standard error response format.
    https://www.rfc-editor.org/rfc/rfc9457.html
    """
    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type."
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type."
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server for this occurrence of the problem."
    )
    detail: Optional[str] = Field(
        default=None,
        description="A human-readable explanation specific to this occurrence of the problem."
    )
    instance: Optional[str] = Field(
        default=None,
        description="A URI reference that identifies the specific occurrence of the problem."
    )
    extensions: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional problem details specific to the API."
    )
